; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=reassociate -S %s | FileCheck %s

define float @fma_pair_with_square_terms(float %b, float %c) {
; CHECK-LABEL: define float @fma_pair_with_square_terms(
; CHECK-SAME: float [[B:%.*]], float [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BB:%.*]] = fmul fast float [[B]], [[B]]
; CHECK-NEXT:    [[CC:%.*]] = fmul fast float [[C]], [[C]]
; CHECK-NEXT:    [[B_CC:%.*]] = fadd fast float [[BB]], [[B]]
; CHECK-NEXT:    [[C_BB:%.*]] = fadd fast float [[B_CC]], [[C]]
; CHECK-NEXT:    [[SUM:%.*]] = fadd fast float [[C_BB]], [[CC]]
; CHECK-NEXT:    ret float [[SUM]]
;
entry:
  %bb = fmul fast float %b, %b
  %cc = fmul fast float %c, %c
  %b.cc = fadd fast float %b, %cc
  %c.bb = fadd fast float %c, %bb
  %sum = fadd fast float %b.cc, %c.bb
  ret float %sum
}
